### ISSUE TITLE
pareselib doesn't include in ver 0.4.2

### ISSUE THREAD

**Issue by own-star** [erlangbureau/exomler#1]
XML = <<"<html key=\"value\">Body</html>">>.
<<"<html key=\"value\">Body</html>">>
exomler:decode(XML).
** exception error: undefined function bstring:trim_left/1
     in function  exomler_dom_decoder:decode/1 (src/exomler_dom_decoder.erl, line 17)

Should add 
{included_applications, [parselib]}
to src/exomler.app.src

**Comment by kostiushkin** [comment]
Yes, unfortunately exomler can only parse the valid XML, like this: 
```
1> XML = <<"<html key=\"value\">Body</html>">>
<<"<html key=\"value\">Body</html>">>
2> exomler:decode(XML).
{<<"html">>,[{<<"key">>,<<"value">>}],[<<"Body">>]}
```

**Comment by kostiushkin** [comment]
Try last commit from master, if it works fine, then i will add new tag 0.5.0
